version: "3"
networks:
  default:
    driver: bridge

services:
  mysql:
    container_name: teste-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./teste-inicio.sql:/docker-entrypoint-initdb.d/inicio.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teste-app
      - MYSQL_USER=user-app
      - MYSQL_PASSWORD=senha-teste-app
  
      
  datapage-api:
    build: ./datapage-api/
    command: npm run dev-start
    env_file: ./datapage-api/.env
    restart: always 
    ports:
      - "3003:3003"
    volumes:
      - ./datapage-api/:/usr/api
    depends_on:
      - mysql


  datapage-ui:
    build: ./datapage-ui/
    command: npm run start
    env_file: ./datapage-ui/.env
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./datapage-ui/:/usr/react
      - ./datapage-ui/node_modules
    environment:
          - NODE_ENV=development
    depends_on:
      - datapage-api